"""Reusable model mixins shared by every table.

Composing these on every entity gives the whole CRM uniform behaviour:
  * IntPkMixin      — auto-incrementing integer primary keys (1, 2, 3, …),
                      generated by a Postgres identity sequence. Human-readable
                      and easy to reference. NOTE: sequential ids are guessable,
                      so don't rely on them being unpredictable for security.
  * TimestampMixin  — created_at / updated_at maintained by the DB, not the app,
                      so values are correct even for raw SQL or other writers.
  * SoftDeleteMixin — logical deletes (deleted_at) preserve history for audit,
                      analytics and undo. The base repository filters these out.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import BigInteger, DateTime, func
from sqlalchemy.orm import Mapped, mapped_column


class IntPkMixin:
    id: Mapped[int] = mapped_column(
        BigInteger,
        primary_key=True,
        autoincrement=True,
    )


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class SoftDeleteMixin:
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None, index=True
    )

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None
