"""enable required postgres extensions

Revision ID: 0001_enable_extensions
Revises:
Create Date: 2026-01-01 00:00:00

The very first migration. Enables pgcrypto for ``gen_random_uuid()`` (used as the
server-side default for UUID primary keys). Run further autogenerated migrations
on top of this with: ``alembic revision --autogenerate -m "create tables"``.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001_enable_extensions"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')


def downgrade() -> None:
    op.execute('DROP EXTENSION IF EXISTS "pgcrypto";')
